# Generated by Django 3.1.7 on 2021-02-26 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_weather_api_key', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_timestamp', models.DateField(default=django.utils.timezone.now)),
                ('request_city', models.CharField(max_length=100)),
                ('request_response_data', models.TextField()),
            ],
        ),
    ]
