# Generated by Django 3.1.7 on 2021-02-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikeys',
            name='open_weather_api_key',
        ),
        migrations.AddField(
            model_name='apikeys',
            name='key_name',
            field=models.CharField(default='Test', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apikeys',
            name='key_value',
            field=models.CharField(default='test', max_length=256),
            preserve_default=False,
        ),
    ]
