# Generated by Django 3.1.7 on 2021-02-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20210226_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='request_city',
            new_name='request_address',
        ),
    ]
